<template>
  <v-dialog v-model="dialog" width="500">
    <template v-slot:activator="{ on, attrs }">
      <v-btn v-bind="attrs" v-on="on" @click="openDialog">
        <span class="hidden-sm-and-down">{{ $t("Import") }}</span>
        <v-icon right>mdi-import</v-icon>
      </v-btn>
    </template>
    <v-card>
      <v-card-title class="headline">
        {{ $t("Import Fleet") }}
      </v-card-title>
      <v-card-text>
        <v-stepper v-model="step" class="stepper">
          <v-stepper-items class="stepper-items">
            <v-stepper-content class="stepper-item" step="1">
              <p>
                {{
                  $t(
                    "This functions allows the import of an entire fleet using a 'shiplist.json' file generated by the HangarEXPLOR web extension."
                  )
                }}
              </p>
              <v-file-input
                accept=".json"
                :rules="rules"
                prepend-icon="mdi-file-import-outline"
                show-size
                :label="$t('Upload shiplist.json')"
                v-model="file"
                :error="fileErrorMessages.length > 0"
                :error-messages="fileErrorMessages"
              ></v-file-input>
            </v-stepper-content>

            <v-stepper-content class="stepper-item" step="2">
              <diV>
                <span>
                  {{ $t("Ships found:") }}
                  :&nbsp;
                </span>
                <span>{{ count }}</span>
              </diV>
              <v-radio-group v-model="importType">
                <v-radio
                  :label="$t('Merge import with existing fleet')"
                  value="merge"
                ></v-radio>
                <v-radio
                  :label="$t('Replace existing fleet')"
                  value="replace"
                ></v-radio>
              </v-radio-group>
            </v-stepper-content>

            <v-stepper-content class="stepper-item" step="3">
            </v-stepper-content>
          </v-stepper-items>
        </v-stepper>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn text @click="dialog = false">{{ $t("Cancel") }}</v-btn>
        <v-btn
          v-if="step < 2"
          color="primary"
          text
          :disabled="nextDisabled"
          @click="nextStep"
          >{{ $t("Next") }}</v-btn
        >
        <v-btn v-if="step == 2" color="primary" text @click="commitImport">{{
          $t("Import")
        }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
export default {
  name: "ImportDialog",
  data: () => ({
    dialog: false,
    step: 1,
    file: null,
    data: null,
    importType: "merge",
    rules: [
      (value) =>
        !value || value.size < 2000000 || "File size should be less than 2 MB!",
    ],
    fileErrorMessages: [],
  }),
  methods: {
    openDialog() {
      this.file = null;
      this.step = 1;
      this.dialog = true;
    },
    nextStep() {
      switch (this.step) {
        case 1:
          this.startImport();
          break;
        default:
          break;
      }
    },
    startImport() {
      this.fileErrorMessages = [];
      this.data = null;
      if (!this.file) {
        return;
      }
      var reader = new FileReader();
      reader.onload = () => {
        this.parseJsonData(reader.result);
      };
      reader.onError = () => {
        this.fileErrorMessages.push(
          this.$t("Error reading import file:") + reader.error
        );
      };
      reader.readAsText(this.file);
    },
    parseJsonData(json) {
      if (!json.includes("ship_code")) {
        this.fileErrorMessages.push(this.$t("Invalid json file!"));
      }
      try {
        this.data = JSON.parse(json);
        this.step = 2;
      } catch (error) {
        this.fileErrorMessages.push(this.$t("Invalid json file: " + error));
      }
    },
    commitImport() {
      if (this.importType == "replace") {
        this.$store.dispatch("clear");
      }
      this.$store.dispatch("import", {
        type: this.importType,
        data: this.data,
      });
      this.dialog = false;
      this.step = 1;
    },
  },
  computed: {
    nextDisabled() {
      switch (this.step) {
        case 1:
          return this.file == null;
        default:
          return true;
      }
    },
    count: (context) => (context.data ? context.data.length : 0),
  },
};
</script>

<style scoped>
.stepper {
  background-color: transparent;
}
.stepper-item {
  padding: 0;
  margin: 0;
}
</style>
